name: WSGAN
channels:
  - defaults
  - pytorch
  - conda-forge  
dependencies:
  - pip=21.2.4
  - python=3.7.3
  - pytorch=1.8.0
  - torchvision=0.9.0
  - pip:
      - jupyter==1.0.0
      - jupyter-client==6.1.5
      - lightning-bolts==0.3.4
      - pillow==8.2.0
      - pytorch-lightning==1.3.8
      - scikit-image==0.17.2
      - scikit-learn==0.23.2
      - scipy==1.5.2
      - numpy==1.19.5
      - tensorboard==2.6.0
      - torchprof==1.3.3
      - torchmetrics==0.4.1
      - torch-fidelity
