name: WSGANpaper
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.16
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - torchvision=0.14.1
  - scikit-learn=1.2.1
  - pytorch-lightning=1.9.4
  - pip:
      - torch-fidelity==0.3.0